apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bank-of-msa

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - databases/accounts-db.yaml
  - databases/ledger-db.yaml
  - services/userservice.yaml
  - services/contacts.yaml
  - services/ledger-writer.yaml
  - services/balance-reader.yaml
  - services/transaction-history.yaml
  - services/frontend.yaml

commonLabels:
  project: bank-of-msa
